" Pathogen setup
" call pathogen#infect()
" call pathogen#helptags()

set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" " plugin on GitHub repo
Plugin 'xolox/vim-easytags'
Plugin 'xolox/vim-misc'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-ragtag'
Plugin 'tpope/vim-surround'
Plugin 'wincent/Command-T'
Plugin 'Raimondi/delimitMate'
Plugin 'vim-scripts/matchit.zip'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'luochen1990/rainbow'
Plugin 'altercation/vim-colors-solarized'
Plugin 'SirVer/ultisnips'
Plugin 'nvie/vim-flake8'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required

" Common options
syntax enable
filetype plugin on
set incsearch
set number
set hlsearch
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set pastetoggle=<F2>
set wrap
set cc=80
set laststatus=2
set completeopt=menuone,longest,preview
" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Colorscheme options
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

" Filetype options
au FileType python set omnifunc=pythoncomplete#Complete
au FileType javascript set omnifunc=javascriptcomplete#CompleteJS sw=2 sts=2 et
au FileType html set sw=2 sts=2 et
au FileType css set omnifunc=csscomplete#CompleteCSS
au FileType xml set omnifunc=xmlcomplete#CompleteTags
au FileType php set omnifunc=phpcomplete#CompletePHP
au BufRead,BufNewFile *.json set filetype=json

" NERDTree options
nnoremap <F12> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen=1

" Tagbar options
let g:tagbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 1

" Css color vim options
let g:cssColorVimDoNotMessMyUpdatetime = 1

" Flake 8 options
autocmd BufWritePost *.py call Flake8()
let g:flake8_ignore="E501,W293"

" Markdown to HTML
nmap <leader>md :%!/usr/bin/markdown <CR>

" Python environment for buildout and virutalenv
let $PYTHONPATH .= ':/home/arjen/.buildout/eggs'
let $PYTHONPATH .= ':$VIRTUAL_ENV/lib/python2.7/site-packages'

" Powerline bindings
set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim

" Syntastic options
let g:syntastic_auto_loc_list=1
let g:syntastic_javascript_jshint_args = '--config /home/arjen/.jshintrc'
let g:syntastic_javascript_checkers=['jshint']
let g:Syntastic_json_checkers=['jsonlint']
let g:syntastic_disabled_filetypes=['html']
let g:syntastic_check_on_open=0
autocmd BufWritePost *.js call SyntasticCheck

let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '!'

" tell easytags to be relaxed about the updatetime
let easytags_updatetime_min = 2000

" rainbow parentheses
let g:rainbow_active = 1

" handle ultisnips / youcompleteme issues
function! g:UltiSnips_Complete()
    call UltiSnips#ExpandSnippet()
    if g:ulti_expand_res == 0
        if pumvisible()
            return "\<C-n>"
        else
            call UltiSnips#JumpForwards()
            if g:ulti_jump_forwards_res == 0
               return "\<TAB>"
            endif
        endif
    endif
    return ""
endfunction

" au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
" let g:UltiSnipsJumpForwardTrigger="<tab>"
" let g:UltiSnipsListSnippets="<c-e>"
